/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProductRouteImport } from './routes/product'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiCrewRouteImport } from './routes/api/crew'
import { Route as ApiGatewayRouteImport } from './routes/api/gateway'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardAttacksRouteImport } from './routes/dashboard.attacks'
import { Route as DashboardCapturesRouteImport } from './routes/dashboard.captures'
import { Route as DashboardEvidenceRouteImport } from './routes/dashboard.evidence'
import { Route as DashboardLoopRouteImport } from './routes/dashboard.loop'
import { Route as DashboardPoliciesRouteImport } from './routes/dashboard.policies'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrewRoute = ApiCrewRouteImport.update({
  id: '/api/crew',
  path: '/api/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayRoute = ApiGatewayRouteImport.update({
  id: '/api/gateway',
  path: '/api/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttacksRoute = DashboardAttacksRouteImport.update({
  id: '/attacks',
  path: '/attacks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCapturesRoute = DashboardCapturesRouteImport.update({
  id: '/captures',
  path: '/captures',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvidenceRoute = DashboardEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoopRoute = DashboardLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/product': typeof ProductRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/crew': typeof ApiCrewRoute
  '/api/gateway': typeof ApiGatewayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/attacks': typeof DashboardAttacksRoute
  '/dashboard/captures': typeof DashboardCapturesRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/loop': typeof DashboardLoopRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/product': typeof ProductRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/crew': typeof ApiCrewRoute
  '/api/gateway': typeof ApiGatewayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/attacks': typeof DashboardAttacksRoute
  '/dashboard/captures': typeof DashboardCapturesRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/loop': typeof DashboardLoopRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/product': typeof ProductRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/crew': typeof ApiCrewRoute
  '/api/gateway': typeof ApiGatewayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/attacks': typeof DashboardAttacksRoute
  '/dashboard/captures': typeof DashboardCapturesRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/loop': typeof DashboardLoopRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/case-studies'
    | '/contact'
    | '/dashboard'
    | '/product'
    | '/skills'
    | '/api/contact'
    | '/api/crew'
    | '/api/gateway'
    | '/api/health'
    | '/api/mcp'
    | '/dashboard/approvals'
    | '/dashboard/attacks'
    | '/dashboard/captures'
    | '/dashboard/evidence'
    | '/dashboard/loop'
    | '/dashboard/policies'
    | '/dashboard/roles'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/case-studies'
    | '/contact'
    | '/product'
    | '/skills'
    | '/api/contact'
    | '/api/crew'
    | '/api/gateway'
    | '/api/health'
    | '/api/mcp'
    | '/dashboard/approvals'
    | '/dashboard/attacks'
    | '/dashboard/captures'
    | '/dashboard/evidence'
    | '/dashboard/loop'
    | '/dashboard/policies'
    | '/dashboard/roles'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/case-studies'
    | '/contact'
    | '/dashboard'
    | '/product'
    | '/skills'
    | '/api/contact'
    | '/api/crew'
    | '/api/gateway'
    | '/api/health'
    | '/api/mcp'
    | '/dashboard/approvals'
    | '/dashboard/attacks'
    | '/dashboard/captures'
    | '/dashboard/evidence'
    | '/dashboard/loop'
    | '/dashboard/policies'
    | '/dashboard/roles'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ProductRoute: typeof ProductRoute
  SkillsRoute: typeof SkillsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiCrewRoute: typeof ApiCrewRoute
  ApiGatewayRoute: typeof ApiGatewayRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crew': {
      id: '/api/crew'
      path: '/api/crew'
      fullPath: '/api/crew'
      preLoaderRoute: typeof ApiCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway': {
      id: '/api/gateway'
      path: '/api/gateway'
      fullPath: '/api/gateway'
      preLoaderRoute: typeof ApiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attacks': {
      id: '/dashboard/attacks'
      path: '/attacks'
      fullPath: '/dashboard/attacks'
      preLoaderRoute: typeof DashboardAttacksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/captures': {
      id: '/dashboard/captures'
      path: '/captures'
      fullPath: '/dashboard/captures'
      preLoaderRoute: typeof DashboardCapturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evidence': {
      id: '/dashboard/evidence'
      path: '/evidence'
      fullPath: '/dashboard/evidence'
      preLoaderRoute: typeof DashboardEvidenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/loop': {
      id: '/dashboard/loop'
      path: '/loop'
      fullPath: '/dashboard/loop'
      preLoaderRoute: typeof DashboardLoopRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policies': {
      id: '/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardAttacksRoute: typeof DashboardAttacksRoute
  DashboardCapturesRoute: typeof DashboardCapturesRoute
  DashboardEvidenceRoute: typeof DashboardEvidenceRoute
  DashboardLoopRoute: typeof DashboardLoopRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardAttacksRoute: DashboardAttacksRoute,
  DashboardCapturesRoute: DashboardCapturesRoute,
  DashboardEvidenceRoute: DashboardEvidenceRoute,
  DashboardLoopRoute: DashboardLoopRoute,
  DashboardPoliciesRoute: DashboardPoliciesRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ProductRoute: ProductRoute,
  SkillsRoute: SkillsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiCrewRoute: ApiCrewRoute,
  ApiGatewayRoute: ApiGatewayRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
